config/routes.rb
RailsPress::Application.routes.draw do
  resources :wp_posts

  resources :wp_users

end

app/models/wp_post.rb
class WpPost < ActiveRecord::Base

  self.primary_key = :ID

  attr_accessible :comment_count, :comment_status, :guid, :menu_order, :ping_status, :pinged, :post_author, :post_content, :post_content_filtered, :post_date, :post_date_gmt, :post_excerpt, :post_mime_type, :post_modified, :post_modified_gmt, :post_name, :post_parent, :post_password, :post_status, :post_title, :post_type, :to_ping

end

app/models/wp_user.rb
class WpUser < ActiveRecord::Base
  self.primary_key = :ID
  attr_accessible :display_name, :user_activation_key, :user_email, :user_login, :user_nicename, :user_pass, :user_registered, :user_status, :user_url

  validates_presence_of :user_login, :user_pass, :user_nicename, :user_email, :user_url, :user_registered, :user_activation_key, :user_status, :display_name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wp_posts_controller.rb
class WpPostsController < ApplicationController
  # GET /wp_posts
  # GET /wp_posts.json
  def index
    @wp_posts = WpPost.where("post_type = ? AND post_status = ?", 'post', 'publish')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wp_posts }
    end
  end

  # GET /wp_posts/1
  # GET /wp_posts/1.json
  def show
    @wp_post = WpPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wp_post }
    end
  end

  # GET /wp_posts/new
  # GET /wp_posts/new.json
  def new
    @wp_post = WpPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wp_post }
    end
  end

  # GET /wp_posts/1/edit
  def edit
    @wp_post = WpPost.find(params[:id])
  end

  # POST /wp_posts
  # POST /wp_posts.json
  def create
    @wp_post = WpPost.new(params[:wp_post])

    respond_to do |format|
      if @wp_post.save
        format.html { redirect_to @wp_post, notice: 'Wp post was successfully created.' }
        format.json { render json: @wp_post, status: :created, location: @wp_post }
      else
        format.html { render action: "new" }
        format.json { render json: @wp_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wp_posts/1
  # PUT /wp_posts/1.json
  def update
    @wp_post = WpPost.find(params[:id])

    respond_to do |format|
      if @wp_post.update_attributes(params[:wp_post])
        format.html { redirect_to @wp_post, notice: 'Wp post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wp_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wp_posts/1
  # DELETE /wp_posts/1.json
  def destroy
    @wp_post = WpPost.find(params[:id])
    @wp_post.destroy

    respond_to do |format|
      format.html { redirect_to wp_posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/wp_users_controller.rb
class WpUsersController < ApplicationController
  # GET /wp_users
  # GET /wp_users.json
  def index
    @wp_users = WpUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wp_users }
    end
  end

  # GET /wp_users/1
  # GET /wp_users/1.json
  def show
    @wp_user = WpUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wp_user }
    end
  end

  # GET /wp_users/new
  # GET /wp_users/new.json
  def new
    @wp_user = WpUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wp_user }
    end
  end

  # GET /wp_users/1/edit
  def edit
    @wp_user = WpUser.find(params[:id])
  end

  # POST /wp_users
  # POST /wp_users.json
  def create
    @wp_user = WpUser.new(params[:wp_user])

    respond_to do |format|
      if @wp_user.save
        format.html { redirect_to @wp_user, notice: 'Wp user was successfully created.' }
        format.json { render json: @wp_user, status: :created, location: @wp_user }
      else
        format.html { render action: "new" }
        format.json { render json: @wp_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wp_users/1
  # PUT /wp_users/1.json
  def update
    @wp_user = WpUser.find(params[:id])

    respond_to do |format|
      if @wp_user.update_attributes(params[:wp_user])
        format.html { redirect_to @wp_user, notice: 'Wp user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wp_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wp_users/1
  # DELETE /wp_users/1.json
  def destroy
    @wp_user = WpUser.find(params[:id])
    @wp_user.destroy

    respond_to do |format|
      format.html { redirect_to wp_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wp_posts_helper.rb
module WpPostsHelper
end

app/helpers/wp_users_helper.rb
module WpUsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPress</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wp_posts/_form.html.erb
<%= form_for(@wp_post) do |f| %>
  <% if @wp_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wp_post.errors.count, "error") %> prohibited this wp_post from being saved:</h2>

      <ul>
      <% @wp_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_author %><br />
    <%= f.number_field :post_author %>
  </div>
  <div class="field">
    <%= f.label :post_date %><br />
    <%= f.datetime_select :post_date %>
  </div>
  <div class="field">
    <%= f.label :post_date_gmt %><br />
    <%= f.datetime_select :post_date_gmt %>
  </div>
  <div class="field">
    <%= f.label :post_content %><br />
    <%= f.text_area :post_content %>
  </div>
  <div class="field">
    <%= f.label :post_title %><br />
    <%= f.text_area :post_title %>
  </div>
  <div class="field">
    <%= f.label :post_excerpt %><br />
    <%= f.text_area :post_excerpt %>
  </div>
  <div class="field">
    <%= f.label :post_status %><br />
    <%= f.text_field :post_status %>
  </div>
  <div class="field">
    <%= f.label :comment_status %><br />
    <%= f.text_field :comment_status %>
  </div>
  <div class="field">
    <%= f.label :ping_status %><br />
    <%= f.text_field :ping_status %>
  </div>
  <div class="field">
    <%= f.label :post_password %><br />
    <%= f.text_field :post_password %>
  </div>
  <div class="field">
    <%= f.label :post_name %><br />
    <%= f.text_field :post_name %>
  </div>
  <div class="field">
    <%= f.label :to_ping %><br />
    <%= f.text_area :to_ping %>
  </div>
  <div class="field">
    <%= f.label :pinged %><br />
    <%= f.text_area :pinged %>
  </div>
  <div class="field">
    <%= f.label :post_modified %><br />
    <%= f.datetime_select :post_modified %>
  </div>
  <div class="field">
    <%= f.label :post_modified_gmt %><br />
    <%= f.datetime_select :post_modified_gmt %>
  </div>
  <div class="field">
    <%= f.label :post_content_filtered %><br />
    <%= f.text_area :post_content_filtered %>
  </div>
  <div class="field">
    <%= f.label :post_parent %><br />
    <%= f.number_field :post_parent %>
  </div>
  <div class="field">
    <%= f.label :guid %><br />
    <%= f.text_field :guid %>
  </div>
  <div class="field">
    <%= f.label :menu_order %><br />
    <%= f.number_field :menu_order %>
  </div>
  <div class="field">
    <%= f.label :post_type %><br />
    <%= f.text_field :post_type %>
  </div>
  <div class="field">
    <%= f.label :post_mime_type %><br />
    <%= f.text_field :post_mime_type %>
  </div>
  <div class="field">
    <%= f.label :comment_count %><br />
    <%= f.number_field :comment_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wp_posts/edit.html.erb
<h1>Editing wp_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @wp_post %> |
<%= link_to 'Back', wp_posts_path %>

app/views/wp_posts/index.html.erb
<h1>Listing wp_posts</h1>

<table>
  <tr>
    <th>Post author</th>
    <th>Post date</th>
    <th>Post date gmt</th>
    <th>Post content</th>
    <th>Post title</th>
    <th>Post excerpt</th>
    <th>Post status</th>
    <th>Comment status</th>
    <th>Ping status</th>
    <th>Post password</th>
    <th>Post name</th>
    <!-- th>To ping</th -->
    <!-- th>Pinged</th -->
    <th>Post modified</th>
    <th>Post modified gmt</th>
    <th>Post content filtered</th>
    <th>Post parent</th>
    <th>Guid</th>
    <th>Menu order</th>
    <th>Post type</th>
    <th>Post mime type</th>
    <th>Comment count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wp_posts.each do |wp_post| %>
  <tr>
    <td><%= wp_post.post_author %></td>
    <td><%= wp_post.post_date %></td>
    <td><%= wp_post.post_date_gmt %></td>
    <td><%= wp_post.post_content %></td>
    <td><%= wp_post.post_title %></td>
    <td><%= wp_post.post_excerpt %></td>
    <td><%= wp_post.post_status %></td>
    <td><%= wp_post.comment_status %></td>
    <td><%= wp_post.ping_status %></td>
    <td><%= wp_post.post_password %></td>
    <td><%= wp_post.post_name %></td>
    <!-- td><%= wp_post.to_ping %></td -->
    <!-- td><%= wp_post.pinged %></td -->
    <td><%= wp_post.post_modified %></td>
    <td><%= wp_post.post_modified_gmt %></td>
    <td><%= wp_post.post_content_filtered %></td>
    <td><%= wp_post.post_parent %></td>
    <td><%= wp_post.guid %></td>
    <td><%= wp_post.menu_order %></td>
    <td><%= wp_post.post_type %></td>
    <td><%= wp_post.post_mime_type %></td>
    <td><%= wp_post.comment_count %></td>
    <td><%= link_to 'Show', wp_post %></td>
    <td><%= link_to 'Edit', edit_wp_post_path(wp_post) %></td>
    <td><%= link_to 'Destroy', wp_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wp post', new_wp_post_path %>

app/views/wp_posts/new.html.erb
<h1>New wp_post</h1>

<%= render 'form' %>

<%= link_to 'Back', wp_posts_path %>

app/views/wp_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post author:</b>
  <%= @wp_post.post_author %>
</p>

<p>
  <b>Post date:</b>
  <%= @wp_post.post_date %>
</p>

<p>
  <b>Post date gmt:</b>
  <%= @wp_post.post_date_gmt %>
</p>

<p>
  <b>Post content:</b>
  <%= @wp_post.post_content %>
</p>

<p>
  <b>Post title:</b>
  <%= @wp_post.post_title %>
</p>

<p>
  <b>Post excerpt:</b>
  <%= @wp_post.post_excerpt %>
</p>

<p>
  <b>Post status:</b>
  <%= @wp_post.post_status %>
</p>

<p>
  <b>Comment status:</b>
  <%= @wp_post.comment_status %>
</p>

<p>
  <b>Ping status:</b>
  <%= @wp_post.ping_status %>
</p>

<p>
  <b>Post password:</b>
  <%= @wp_post.post_password %>
</p>

<p>
  <b>Post name:</b>
  <%= @wp_post.post_name %>
</p>

<p>
  <b>To ping:</b>
  <%= @wp_post.to_ping %>
</p>

<p>
  <b>Pinged:</b>
  <%= @wp_post.pinged %>
</p>

<p>
  <b>Post modified:</b>
  <%= @wp_post.post_modified %>
</p>

<p>
  <b>Post modified gmt:</b>
  <%= @wp_post.post_modified_gmt %>
</p>

<p>
  <b>Post content filtered:</b>
  <%= @wp_post.post_content_filtered %>
</p>

<p>
  <b>Post parent:</b>
  <%= @wp_post.post_parent %>
</p>

<p>
  <b>Guid:</b>
  <%= @wp_post.guid %>
</p>

<p>
  <b>Menu order:</b>
  <%= @wp_post.menu_order %>
</p>

<p>
  <b>Post type:</b>
  <%= @wp_post.post_type %>
</p>

<p>
  <b>Post mime type:</b>
  <%= @wp_post.post_mime_type %>
</p>

<p>
  <b>Comment count:</b>
  <%= @wp_post.comment_count %>
</p>


<%= link_to 'Edit', edit_wp_post_path(@wp_post) %> |
<%= link_to 'Back', wp_posts_path %>

app/views/wp_users/_form.html.erb
<%= form_for(@wp_user) do |f| %>
  <% if @wp_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wp_user.errors.count, "error") %> prohibited this wp_user from being saved:</h2>

      <ul>
      <% @wp_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_login %><br />
    <%= f.text_field :user_login %>
  </div>
  <div class="field">
    <%= f.label :user_pass %><br />
    <%= f.text_field :user_pass %>
  </div>
  <div class="field">
    <%= f.label :user_nicename %><br />
    <%= f.text_field :user_nicename %>
  </div>
  <div class="field">
    <%= f.label :user_email %><br />
    <%= f.text_field :user_email %>
  </div>
  <div class="field">
    <%= f.label :user_url %><br />
    <%= f.text_field :user_url %>
  </div>
  <div class="field">
    <%= f.label :user_registered %><br />
    <%= f.datetime_select :user_registered %>
  </div>
  <div class="field">
    <%= f.label :user_activation_key %><br />
    <%= f.text_field :user_activation_key %>
  </div>
  <div class="field">
    <%= f.label :user_status %><br />
    <%= f.number_field :user_status %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wp_users/edit.html.erb
<h1>Editing wp_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @wp_user %> |
<%= link_to 'Back', wp_users_path %>

app/views/wp_users/index.html.erb
<h1>Listing wp_users</h1>

<table>
  <tr>
    <th>User login</th>
    <th>User pass</th>
    <th>User nicename</th>
    <th>User email</th>
    <th>User url</th>
    <th>User registered</th>
    <th>User activation key</th>
    <th>User status</th>
    <th>Display name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wp_users.each do |wp_user| %>
  <tr>
    <td><%= wp_user.user_login %></td>
    <td><%= wp_user.user_pass %></td>
    <td><%= wp_user.user_nicename %></td>
    <td><%= wp_user.user_email %></td>
    <td><%= wp_user.user_url %></td>
    <td><%= wp_user.user_registered %></td>
    <td><%= wp_user.user_activation_key %></td>
    <td><%= wp_user.user_status %></td>
    <td><%= wp_user.display_name %></td>
    <td><%= link_to 'Show', wp_user %></td>
    <td><%= link_to 'Edit', edit_wp_user_path(wp_user) %></td>
    <td><%= link_to 'Destroy', wp_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wp user', new_wp_user_path %>

app/views/wp_users/new.html.erb
<h1>New wp_user</h1>

<%= render 'form' %>

<%= link_to 'Back', wp_users_path %>

app/views/wp_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User login:</b>
  <%= @wp_user.user_login %>
</p>

<p>
  <b>User pass:</b>
  <%= @wp_user.user_pass %>
</p>

<p>
  <b>User nicename:</b>
  <%= @wp_user.user_nicename %>
</p>

<p>
  <b>User email:</b>
  <%= @wp_user.user_email %>
</p>

<p>
  <b>User url:</b>
  <%= @wp_user.user_url %>
</p>

<p>
  <b>User registered:</b>
  <%= @wp_user.user_registered %>
</p>

<p>
  <b>User activation key:</b>
  <%= @wp_user.user_activation_key %>
</p>

<p>
  <b>User status:</b>
  <%= @wp_user.user_status %>
</p>

<p>
  <b>Display name:</b>
  <%= @wp_user.display_name %>
</p>


<%= link_to 'Edit', edit_wp_user_path(@wp_user) %> |
<%= link_to 'Back', wp_users_path %>